version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/codedotnet.web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/codedotnet.compiler"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
